name: Branch - Build & Test
on:
  push:
    branches-ignore:
      - main

env:
  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  NODE_VERSION: 20

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Prettier Check
        run: npx prettier . --check

      - name: Lint
        run: npx eslint './**' --fix

      - name: Build
        run: npm run build
