name: Branch - Build & Test
on:
  push:
    branches-ignore:
      - main

env:
  NODE_VERSION: 20

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-checkout-and-setup.yml@1.0.3
        with:
          node-version: ${{env.NODE_VERSION}}
