name: Branch - Build & Test
on:
  push:
    branches-ignore:
      - main

jobs:
  build-test:
    name: Build & Test
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-checkout-setup-lint-build.yml@v1.0.12
