name: Main - Build, Test, Update Release & Publish

on:
  push:
    branches:
      - main

env:
  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  NODE_VERSION: 20

#Move these permissions into the reusable
permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build-test:
    name: Build & Test
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-checkout-and-setu.yml@1.0.3
    with:
      node-version: ${{env.NODE_VERSION}}

  update-release:
    name: Update Release
    needs: build-test
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-update-release.yml@1.0.3
    with:
      package-name: '@ecainternational/eca-design-tokens'

  publish:
    name: Publish NPM Package
    needs: update-release
    if: ${{ needs.update-release.outputs.release_created }}
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-publish-npm-package.yml@1.0.3
    with:
      build-directory: dist
