name: Main - Build, Test, Update Release & Publish

on:
  push:
    branches:
      - main

env:
  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build-test:
    name: Build & Test
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-checkout-setup-lint-build.yml@v1.0.6

  update-release:
    name: Update Release
    needs: build-test
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-update-release.yml@v1.0.6
    with:
      package-name: '@ecainternational/eca-design-tokens'

  publish:
    name: Publish NPM Package
    needs: update-release
    if: ${{ needs.update-release.outputs.release_created }}
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-publish-npm-package.yml@v1.0.6
    with:
      build-directory: dist
