name: Build, Test, Update Release & Publish

on:
  push:
    branches:
      - main

env:
  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  NODE_VERSION: 20

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Prettier Check
        run: npx prettier . --check

      - name: Build
        run: npm run build

  update-release:
    name: Update Release PR
    needs: build-test
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Run Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          pull-request-title-pattern: 'Release${component} ${version}'
          release-type: node
          package-name: '@ecainternational/eca-design-tokens'

  publish:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    needs: update-release
    if: ${{ needs.update-release.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish NPM Package
        run: |
          npx clear-package-json package.json > dist/package.json --fields "type, files, private, publishConfig, peerDependencies, peerDependenciesMeta"
          cd dist
          npm publish
