name: Publish Package
on:
  push:
    branches:
      - main

env:
  VERSION: 1.0.${{github.run_number}}      

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish V${{env.VERSION}}
        run: |
          git config user.email "<an email address>"
          git config user.name "<a name>"
          npm version $VERSION
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
