name: Publish Package
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [main]

env:
  VERSION: 1.0.${{github.run_number}}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Prettier Check
        run: npx prettier . --check

      - name: Build
        run: npm run build

      - name: Publish v${{env.VERSION}}
        run: |
          git config user.email "github@actions.com"
          git config user.name "Github Actions"
          npm version $VERSION
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
