name: Update Release PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    name: Run Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Prettier Check
        run: npx prettier . --check

      - name: Build
        run: npm run build

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          pull-request-title: 'Release${component} ${version}'
          release-type: node
          package-name: '@ecainternational/eca-design-tokens'

      - name: Publish NPM Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
